# Generated by Django 3.1 on 2022-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220513_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('cloth_image', models.ImageField(default='/images/girl1.jpg', upload_to='images')),
                ('category_type', models.TextField(max_length=50)),
            ],
        ),
    ]
