# Generated by Django 4.0.4 on 2022-05-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_mycategory_alter_all_category_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('item_image', models.ImageField(default='/images/girl1.jpg', upload_to='images')),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.mycategory')),
            ],
        ),
    ]
