# Generated by Django 3.1 on 2022-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20220519_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='user_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
