# Generated by Django 3.1 on 2022-05-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_userreg_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.userreg'),
        ),
    ]
